name: Add Item
description: Suggest a new item for the awesome list
title: "Add: [Item Name]"
labels: ["addition"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an item! Please fill out the details below.

  - type: input
    id: name
    attributes:
      label: Item Name
      description: The name of the resource
      placeholder: "Example Tool"
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: Link to the resource
      placeholder: "https://example.com"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description ending with a period (one sentence)
      placeholder: "A tool that helps you do X more efficiently."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which section should this go in?
      options:
        - Official Resources
        - Mod Managers
        - Framework Mods
        - Quality of Life
        - Performance
        - UI and Interface
        - Combat
        - Vanilla Expanded
        - Content Expansion
        - Mod Collections
        - Modding Resources
        - Communities
        - Related
        - Suggest new category
    validations:
      required: true

  - type: textarea
    id: experience
    attributes:
      label: Your Experience
      description: How have you used this resource?
      placeholder: "I've been using this for..."
    validations:
      required: false
